### ISSUE TITLE
[MVP] `linguam/schemam/lid` (Gerar página de entrada de cada esquema de dados, usando Jekyll)

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/Auxilium-Humanitarium-API#14]
Tópico sobre [Produto Mínimo Viável (em inglês: MVP)](https://pt.wikipedia.org/wiki/Produto_vi%C3%A1vel_m%C3%ADnimo) de gerar a página de entrada de cada esquema de dados.

### Referencia inicial

Atualmente tivemos que criar um plugin Jekyll para poder 'expandir' os arquivos YAML, por exemplo:

```yaml
## # _data/api.yml
# (...)

### [linguam]/api/UN ___________________________________________________________

## -----------------------------------------------------------------------------
- xdefallo: /mul-Zyyy/api/UN/HDX/
  xdefallo_est: 1
  linguam: mul-Zyyy  # mul-Zyyy
  typum: api
  gid: UN
  lid: HDX # _[por] xdefallo_est: 1, logo lid é forçado manualmente [por]_
  title: "Alternātīvum pāginam: {% _🗣️ 📝eng-Latn📝 Hapi_api_UN_HDX_titulum 📝eng-Latn📝 🗣️_ %}"
  # title: "Index: {% _🗣️ 📝eng-Latn📝 Hapi_api_UN_HDX_titulum 📝eng-Latn📝 🗣️_ %}"
  noindex: true
  # HAPI_api_UN_HDX

- xdefallo: /mul-Zyyy/api/UN/HDX/
  linguam: eng-Latn
  typum: api
  gid: UN
  lid: '{% _🗣️ 📝eng-Latn📝 Hapi_api_UN_HDX_slug 📝eng-Latn📝 🗣️_ %}'
  openapi_filum: /api/UN/HDX/eng/openapi.yaml
  # title: HDX - The Humanitarian Data Exchange API
  title: '{% _🗣️ 📝eng-Latn📝 Hapi_api_UN_HDX_titulum 📝eng-Latn📝 🗣️_ %}'
  opus_in_progressu: true
  noindex: true

- xdefallo: /mul-Zyyy/api/UN/HDX/
  linguam: por-Latn
  typum: api
  gid: UN
  lid: '{% _🗣️ 📝por-Latn📝 Hapi_api_UN_HDX_slug 📝por-Latn📝 🗣️_ %}'
  openapi_filum: /api/UN/HDX/eng/openapi.yaml # TODO: _[por] Criar uma versão em português [por]_
  # title: HDX - The Humanitarian Data Exchange API
  title: '{% _🗣️ 📝por-Latn📝 Hapi_api_UN_HDX_titulum 📝por-Latn📝 🗣️_ %}'
  noindex: true

# (...)
```

Gera o seguinte sitemap

```xml
  <!-- /sitemap.xml -->
  <!-- (...) -->
  
  <url>
    <loc>/mul-Zyyy/api/UN/HDX/</loc>
    <lastmod>2021-06-14T02:07:48-03:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.1</priority>
    <xhtml:link
      rel="alternate" hreflang="x-default"
      href="/mul-Zyyy/api/UN/HDX/" />
    <xhtml:link
      rel="alternate" hreflang="en"
      href="/eng-Latn/api/UN/humanitarian-data-exchange/" />
    <xhtml:link
      rel="alternate" hreflang="pt"
      href="/por-Latn/api/UN/humanitarian-data-exchange/" />
    <xhtml:link
      rel="alternate" hreflang="ar"
      href="/arb-Arab/api/UN/%D8%A7%D8%AE%D8%AA%D8%A8%D8%A7%D8%B1%D8%A7%D8%AA/" />
  </url>
  
  <!-- (...) -->
    
```

### O que, idealmente, deveria ser feito

Como a ideia é facilitar para deixar o máximo de trabalho para pessoas tradutoras, inicialmente temos que pelo menos replicar o que é feito com as páginas HTML da API, mas agora para schemas.

Porém os arquivos YAML de API são um pouco repetitivos. Isso quer dizer que a nova versão dessa logica em ruby precisa implementar algumas melhorias.

Isso vai dar trabalho. Porém vale a pena fazer isso **antes** de expandir o projeto.
